// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fckhisiclzpkkqgyhtmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZja2hpc2ljbHpwa2txZ3lodG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODc5MzQsImV4cCI6MjA3MzM2MzkzNH0.mScQO0CNr4igvtpJw_u8sz4IAyhx0CC6T_vw5c49DHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});